// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace RCMessageKitQs.Views
{
	public partial class PictureView : UIViewController
	{
        public UIImage pathImage;
        
		public PictureView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            myImageView.Image = pathImage;
        }
	}
}
